name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: "3.9"

  main:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          python-version: "3.9"

      - name: Unit Tests
        run: coverage run -m pytest -s tests

      - name: Test Coverage
        run: coverage report --fail-under=96

      - name: Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit run --all-files

  test-matrix:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Test Matrix
        run: |
          pytest -s tests
          pre-commit run mypy --all-files
