name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

# TODO: Use some kind of cache to speed up running.
jobs:
  test-main-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Unit Tests
        run: coverage run -m pytest -s tests

      - name: Test Coverage
        run: coverage report --fail-under=96

      - name: Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit run --all-files

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run Test Matrix
        run: |
          pytest -s tests
          pre-commit run mypy --all-files
